# Generated by Django 4.1.4 on 2023-01-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_userssettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userssettings",
            name="hide_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userssettings",
            name="darkmode",
            field=models.BooleanField(default=True),
        ),
    ]
