# Generated by Django 4.1.4 on 2023-01-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userssettings",
            name="users_display_after_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
