# Generated by Django 4.1.4 on 2023-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_userssettings_users_display_after_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userssettings",
            name="filter_by_deadline",
            field=models.BooleanField(default=True),
        ),
    ]
