# Generated by Django 4.1.4 on 2023-01-02 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_userssettings_filter_by_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userssettings",
            name="users_display_after_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
